apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: nestjs-demo
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
  storageClassName: vultr-block-storage
